In [1]:
import pandas as pd

In [3]:
import numpy as np

In [22]:
print('hello')

hello

In [31]:
df = pd.read_csv('/Users/dadsgift/Downloads/LnT_Helmet_Survey_Raw.csv')

In [33]:
df.head()

,Respondent_ID,Name,Age,Gender,Place,Date,Safety_Device,Helemt_Frequency,Most_Vulnerable_User,ISI_Awareness,Youth_Role,Speed_Limit_Knowledge,Helmet_Prevention_belief,Helmet_Buying_Factor,Pillion_Helmet,Mirror_Importance,Helmet_Type,Influenced_Others,Media_Influence
0,1.0,Govind Yadav,19.0,M,DTU,10/12/2024,NaN,Always,Two Wheeler,No,Yes,25 KMPH,No,Safety,Always,Very Useful,Standard(ISI Marked),Yes,Yes
1,2.0,Bhavya,20.0,M,DTU,10/12/2024,Quality Helmet,Sometime,Two Wheeler,No,Yes,25 KMPH,Yes,Safety,Always,Very Useful,Standard(ISI Marked),No,Yes
2,3.0,Abhishek Kumar,21.0,M,DTU,11/12/2024,Quality Helmet,Always,Two Wheeler,No,Yes,25 KMPH,Yes,Safety,Never,Very Useful,Standard(ISI Marked),Yes,No
3,4.0,Gupreet,20.0,M,DTU,10/12/2024,Quality Helmet,Always,Two Wheeler,No,Yes,30 KMPH,Yes,Safety,Never,Sometime Useful,Standard(ISI Marked),Yes,No
4,5.0,Mayank Yadav,21.0,M,DTU,10/12/2024,NaN,Always,Two Wheeler,No,Yes,25 KMPH,Yes,Price,Never,Sometime Useful,Standard(ISI Marked),No,Yes

In [37]:
df.shape

(46, 19)

In [39]:
df.columns

Index(['Respondent_ID', 'Name', 'Age', 'Gender ', 'Place ', 'Date',
       'Safety_Device', 'Helemt_Frequency', 'Most_Vulnerable_User',
       'ISI_Awareness', 'Youth_Role', 'Speed_Limit_Knowledge',
       'Helmet_Prevention_belief', 'Helmet_Buying_Factor', 'Pillion_Helmet',
       'Mirror_Importance', 'Helmet_Type', 'Influenced_Others',
       'Media_Influence'],
      dtype='object')

In [41]:
df.info

<bound method DataFrame.info of     Respondent_ID             Name   Age Gender  Place         Date  \
0             1.0     Govind Yadav  19.0       M    DTU  10/12/2024
1             2.0           Bhavya  20.0       M    DTU  10/12/2024
2             3.0   Abhishek Kumar  21.0       M    DTU  11/12/2024
3             4.0          Gupreet  20.0       M    DTU  10/12/2024
4             5.0     Mayank Yadav  21.0       M    DTU  10/12/2024
5             6.0          Nikshep  23.0       M    DTU  10/12/2024
6             7.0  Shashank Chabey  22.0       M    DTU  11/12/2024
7             8.0           Tushar  21.0       M    DTU  11/12/2024
8             9.0           Kalash  23.0       M    DTU  11/12/2024
9            10.0           Apoorv  22.0       M    DTU  11/12/2024
10           11.0       Kalicharan  33.0       M    DTU  10/12/2024
11           12.0           Akshit  21.0       M    DTU  10/12/2024
12           13.0            Parth  21.0       M    DTU  11/12/2024
13           14.0         Parveen   38.0       M    DTU  10/12/2024
14           15.0           Lavya   18.0       M    DTU  11/12/2024
15           16.0        Abhishek   21.0       M    DTU  10/12/2024
16           17.0            Sajel  23.0       M    DTU  10/12/2024
17           18.0           Akshay  20.0       M    DTU  10/12/2024
18           19.0          Sambhav  20.0       M    DTU  10/12/2024
19           20.0          Vaibhav  20.0       M    DTU  10/12/2024
20           21.0         Abhishek  22.0       M    DTU  10/12/2024
21           22.0            Shubh  22.0       M    DTU  10/12/2024
22           23.0           Gaurav  21.0       M    DTU  11/12/2024
23           24.0            Nancy  26.0       F    DTU  11/12/2024
24           25.0           Akarsh  21.0       M    DTU  10/12/2024
25           26.0          Anvesha  21.0       F    DTU  10/12/2024
26           27.0             Aman  20.0       M    DTU  10/12/2024
27           28.0           Awanit  20.0       M    DTU  10/12/2024
28           29.0           Kushal  20.0       M    DTU  10/12/2024
29           30.0           Manish  20.0       M    DTU  10/12/2024
30           31.0            Anish  20.0       M    DTU  10/12/2024
31           32.0           Anshul  20.0       M    DTU  10/12/2024
32           33.0         Abhishek  20.0       M    DTU  10/12/2024
33           34.0           Saumik  20.0       M    DTU  10/12/2024
34           35.0         Himanshu  21.0       M    DTU  10/12/2024
35           36.0     Hemang Verma  22.0       M    DTU  10/12/2024
36           37.0            Harsh  20.0       M    DTU  10/12/2024
37           38.0           Hardik  20.0       M    DTU  10/12/2024
38           39.0           Namrat  20.0       M    DTU  10/12/2024
39           40.0           Aryan   21.0       M    DTU  10/12/2024
40           41.0            Tannu  18.0       F    DTU  10/12/2024
41           42.0         Anshuman  21.0       M    DTU  10/12/2024
42           43.0            Jatin  20.0       M    DTU  10/12/2024
43           44.0            Rahul  20.0       M    DTU  10/12/2024
44           45.0           Akshat  20.0       M    DTU  10/12/2024
45            NaN              NaN   NaN     NaN    NaN         NaN

     Safety_Device Helemt_Frequency Most_Vulnerable_User ISI_Awareness  \
0              NaN           Always          Two Wheeler            No
1   Quality Helmet         Sometime          Two Wheeler            No
2   Quality Helmet           Always          Two Wheeler            No
3   Quality Helmet           Always          Two Wheeler            No
4              NaN           Always          Two Wheeler            No
5              NaN           Always             Cyclists            No
6   Quality Helmet           Always             Cyclists           Yes
7   Quality Helmet         Sometime          Two Wheeler            No
8              NaN           Always          Two Wheeler            No
9   Quality Helmet           Always          Two Wheeler            No
10             NaN           Always          Two Wheeler            No
11  Quality Helmet           Always          Two Wheeler            No
12  Quality Helmet           Always          Two Wheeler            No
13  Quality Helmet           Always          Pedestrians           Yes
14  Quality Helmet           Always          Two Wheeler            No
15  Quality Helmet      When Needed          Two Wheeler            No
16  Quality Helmet      When Needed          Two Wheeler            No
17  Quality Helmet           Always             Cyclists           Yes
18  Quality Helmet           Always             Cyclists            No
19  Quality Helmet           Always          Two Wheeler           Yes
20  Quality Helmet      When Needed           Car Driver           Yes
21  Quality Helmet      When Needed          Pedestrians            No
22             NaN           Always          Two Wheeler           Yes
23  Quality Helmet           Always           Car Driver            No
24  Quality Helmet           Always          Pedestrians           Yes
25  Quality Helmet           Always             Cyclists            No
26  Quality Helmet           Always             Cyclists           Yes
27  Quality Helmet           Always             Cyclists           Yes
28  Quality Helmet           Always             Cyclists           Yes
29  Quality Helmet           Always          Pedestrians           Yes
30  Quality Helmet           Always             Cyclists           Yes
31  Quality Helmet           Always             Cyclists           Yes
32  Quality Helmet           Always          Pedestrians           Yes
33             NaN           Always          Two Wheeler            No
34  Quality Helmet           Always             Cyclists           Yes
35  Quality Helmet           Always             Cyclists           Yes
36  Quality Helmet      When Needed             Cyclists           Yes
37  Quality Helmet           Always          Two Wheeler           Yes
38  Quality Helmet           Always             Cyclists           Yes
39  Quality Helmet           Always             Cyclists           Yes
40  Quality Helmet      When Needed           Car Driver           Yes
41  Quality Helmet           Always             Cyclists           Yes
42             NaN      When Needed           Car Driver            No
43  Quality Helmet           Always          Two Wheeler           Yes
44  Quality Helmet         Sometime          Two Wheeler           Yes
45             NaN              NaN                  NaN           NaN

   Youth_Role Speed_Limit_Knowledge Helmet_Prevention_belief  \
0         Yes               25 KMPH                       No
1         Yes               25 KMPH                      Yes
2         Yes               25 KMPH                      Yes
3         Yes               30 KMPH                      Yes
4         Yes               25 KMPH                      Yes
5         Yes               40 KMPH                      Yes
6         Yes               60 KMPH                      Yes
7         Yes               30 KMPH                      Yes
8         Yes               25 KMPH                      Yes
9         Yes               25 KMPH                      Yes
10        Yes               25 KMPH                      Yes
11        Yes               25 KMPH                      Yes
12        Yes               40 KMPH                      Yes
13        Yes               25 KMPH                      Yes
14        Yes               25 KMPH                      Yes
15        Yes               25 KMPH                      Yes
16        Yes               25 KMPH                      Yes
17        Yes               40 KMPH                      Yes
18        Yes               30 KMPH                      Yes
19        Yes               30 KMPH                      Yes
20         No               30 KMPH                      Yes
21        Yes               40 KMPH                      Yes
22        Yes               25 KMPH                      Yes
23        Yes               30 KMPH                      Yes
24        Yes               30 KMPH                      Yes
25        Yes               25 KMPH                      Yes
26         No               30 KMPH                      Yes
27         No               25 KMPH                      Yes
28        Yes               40 KMPH                      Yes
29        Yes               30 KMPH                      Yes
30        Yes               30 KMPH                      Yes
31        Yes               30 KMPH                      Yes
32        Yes               40 KMPH                      Yes
33        Yes               40 KMPH                      Yes
34        Yes               25 KMPH                      Yes
35        Yes               25 KMPH                       No
36        Yes               25 KMPH                       No
37        Yes               25 KMPH                      Yes
38        Yes               25 KMPH                       No
39        Yes               30 KMPH                      Yes
40        Yes               30 KMPH                      Yes
41        Yes               25 KMPH                      Yes
42        Yes               30 KMPH                      Yes
43        Yes               30 KMPH                      Yes
44        Yes               25 KMPH                      Yes
45        NaN                   NaN                      NaN

   Helmet_Buying_Factor Pillion_Helmet Mirror_Importance  \
0                Safety         Always       Very Useful
1                Safety         Always       Very Useful
2                Safety          Never       Very Useful
3                Safety          Never   Sometime Useful
4                 Price          Never   Sometime Useful
5                Safety      Sometimes   Sometime Useful
6                Safety         Choice   Sometime Useful
7                Safety         Choice       Very Useful
8                 Price      Sometimes       Very Useful
9                Safety         Choice       Very Useful
10               Safety         Always   Sometime Useful
11               Safety      Sometimes       Very Useful
12               Safety      Sometimes   Sometime Useful
13               Safety         Always   Sometime Useful
14               Safety      Sometimes       Very Useful
15               Safety          Never       Very Useful
16               Safety      Sometimes       Very Useful
17                Style         Always   Sometime Useful
18                Price         Always       Very Useful
19               Safety         Always       Very Useful
20               Safety         Always   Sometime Useful
21                Price         Always       Very Useful
22                Style         Always       Very Useful
23               Safety         Always       Very Useful
24               Safety         Always   Sometime Useful
25               Safety         Always       Very Useful
26               Safety         Always       Very Useful
27               Safety         Always       Very Useful
28               Safety         Always       Very Useful
29                Price         Always       Very Useful
30                Price         Always       Very Useful
31                Price         Always       Very Useful
32                Price         Always       Very Useful
33               Safety      Sometimes   Sometime Useful
34                Price      Sometimes       Very Useful
35                Price         Always        Not Useful
36                Price      Sometimes       Very Useful
37               Safety          Never       Very Useful
38                Brand         Always       Very Useful
39               Safety      Sometimes       Very Useful
40               Safety      Sometimes       Very Useful
41               Safety         Always       Very Useful
42                Brand         Always        Not Useful
43                Brand         Always       Very Useful
44               Safety      Sometimes       Very Useful
45                  NaN            NaN               NaN

                 Helmet_Type Influenced_Others Media_Influence
0       Standard(ISI Marked)               Yes             Yes
1       Standard(ISI Marked)                No             Yes
2       Standard(ISI Marked)               Yes              No
3       Standard(ISI Marked)               Yes              No
4       Standard(ISI Marked)                No             Yes
5       Standard(ISI Marked)               Yes             Yes
6       Standard(ISI Marked)                No             Yes
7       Standard(ISI Marked)               Yes             Yes
8       Standard(ISI Marked)                No             Yes
9       Standard(ISI Marked)               Yes             Yes
10  Non-Standard(Local Mode)               Yes             Yes
11      Standard(ISI Marked)               Yes             Yes
12      Standard(ISI Marked)                No              No
13      Standard(ISI Marked)               Yes             Yes
14  Non-Standard(Local Mode)                No             Yes
15      Standard(ISI Marked)                No              No
16      Standard(ISI Marked)               Yes              No
17  Non-Standard(Local Mode)               Yes             Yes
18      Standard(ISI Marked)               Yes              No
19  Non-Standard(Local Mode)               Yes             Yes
20  Non-Standard(Local Mode)               Yes             Yes
21      Standard(ISI Marked)               Yes             Yes
22      Standard(ISI Marked)               Yes             Yes
23      Standard(ISI Marked)                No             Yes
24      Standard(ISI Marked)               Yes             Yes
25      Standard(ISI Marked)               Yes             Yes
26      Standard(ISI Marked)               Yes             Yes
27      Standard(ISI Marked)               Yes             Yes
28      Standard(ISI Marked)               Yes             Yes
29      Standard(ISI Marked)               Yes             Yes
30      Standard(ISI Marked)               Yes             Yes
31      Standard(ISI Marked)               Yes             Yes
32      Standard(ISI Marked)               Yes             Yes
33  Non-Standard(Local Mode)               Yes              No
34                 Topi Type               Yes             Yes
35      Standard(ISI Marked)                No              No
36      Standard(ISI Marked)               Yes              No
37      Standard(ISI Marked)                No             Yes
38      Standard(ISI Marked)               Yes             Yes
39      Standard(ISI Marked)                No             Yes
40                Half Faced               Yes              No
41      Standard(ISI Marked)               Yes              No
42      Standard(ISI Marked)                No             Yes
43  Non-Standard(Local Mode)               Yes             Yes
44      Standard(ISI Marked)               Yes             Yes
45                       NaN               NaN             NaN  >

In [43]:
df.isnull().sum()

Respondent_ID               1
Name                        1
Age                         1
Gender                      1
Place                       1
Date                        1
Safety_Device               9
Helemt_Frequency            1
Most_Vulnerable_User        1
ISI_Awareness               1
Youth_Role                  1
Speed_Limit_Knowledge       1
Helmet_Prevention_belief    1
Helmet_Buying_Factor        1
Pillion_Helmet              1
Mirror_Importance           1
Helmet_Type                 1
Influenced_Others           1
Media_Influence             1
dtype: int64

In [49]:
df["Helmet_Type"] = df["Helmet_Type"].fillna("Unknown")

In [51]:
df.duplicated().sum()

0

In [57]:
df["Gender "].unique()

array(['M', 'F', nan], dtype=object)

In [59]:
df["Gender "] = (df["Gender "].str.lower().str.strip())

In [87]:
df["Gender "] = df["Gender "].replace({'m':'Male','f':'Female','nan':'NA'})

In [67]:
df["Helemt_Frequency"].unique()

array(['Always', 'Sometime', 'When Needed', nan], dtype=object)

In [73]:
df["Helemt_Frequency"] = (df["Helemt_Frequency"].str.capitalize())

In [75]:
df["Age"].dtype

dtype('float64')

In [77]:
df["Age"] = pd.to_numeric(df["Age"],errors="coerce")

In [79]:
def age_group(age):

    if age <=20:
        return "18-20"

    elif age <=25:
        return "21-25"

    else:
        return "26+"


df["Age_Group"] = df["Age"].apply(age_group)

In [81]:
df.head()

,Respondent_ID,Name,Age,Gender,Place,Date,Safety_Device,Helemt_Frequency,Most_Vulnerable_User,ISI_Awareness,Youth_Role,Speed_Limit_Knowledge,Helmet_Prevention_belief,Helmet_Buying_Factor,Pillion_Helmet,Mirror_Importance,Helmet_Type,Influenced_Others,Media_Influence,Age_Group
0,1.0,Govind Yadav,19.0,m,DTU,10/12/2024,NaN,Always,Two Wheeler,No,Yes,25 KMPH,No,Safety,Always,Very Useful,Standard(ISI Marked),Yes,Yes,18-20
1,2.0,Bhavya,20.0,m,DTU,10/12/2024,Quality Helmet,Sometime,Two Wheeler,No,Yes,25 KMPH,Yes,Safety,Always,Very Useful,Standard(ISI Marked),No,Yes,18-20
2,3.0,Abhishek Kumar,21.0,m,DTU,11/12/2024,Quality Helmet,Always,Two Wheeler,No,Yes,25 KMPH,Yes,Safety,Never,Very Useful,Standard(ISI Marked),Yes,No,21-25
3,4.0,Gupreet,20.0,m,DTU,10/12/2024,Quality Helmet,Always,Two Wheeler,No,Yes,30 KMPH,Yes,Safety,Never,Sometime Useful,Standard(ISI Marked),Yes,No,18-20
4,5.0,Mayank Yadav,21.0,m,DTU,10/12/2024,NaN,Always,Two Wheeler,No,Yes,25 KMPH,Yes,Price,Never,Sometime Useful,Standard(ISI Marked),No,Yes,21-25

In [85]:
df.head()

,Respondent_ID,Name,Age,Gender,Place,Date,Safety_Device,Helemt_Frequency,Most_Vulnerable_User,ISI_Awareness,Youth_Role,Speed_Limit_Knowledge,Helmet_Prevention_belief,Helmet_Buying_Factor,Pillion_Helmet,Mirror_Importance,Helmet_Type,Influenced_Others,Media_Influence,Age_Group
0,1.0,Govind Yadav,19.0,Male,DTU,10/12/2024,NaN,Always,Two Wheeler,No,Yes,25 KMPH,No,Safety,Always,Very Useful,Standard(ISI Marked),Yes,Yes,18-20
1,2.0,Bhavya,20.0,Male,DTU,10/12/2024,Quality Helmet,Sometime,Two Wheeler,No,Yes,25 KMPH,Yes,Safety,Always,Very Useful,Standard(ISI Marked),No,Yes,18-20
2,3.0,Abhishek Kumar,21.0,Male,DTU,11/12/2024,Quality Helmet,Always,Two Wheeler,No,Yes,25 KMPH,Yes,Safety,Never,Very Useful,Standard(ISI Marked),Yes,No,21-25
3,4.0,Gupreet,20.0,Male,DTU,10/12/2024,Quality Helmet,Always,Two Wheeler,No,Yes,30 KMPH,Yes,Safety,Never,Sometime Useful,Standard(ISI Marked),Yes,No,18-20
4,5.0,Mayank Yadav,21.0,Male,DTU,10/12/2024,NaN,Always,Two Wheeler,No,Yes,25 KMPH,Yes,Price,Never,Sometime Useful,Standard(ISI Marked),No,Yes,21-25

In [89]:
df.isnull().sum()

Respondent_ID               1
Name                        1
Age                         1
Gender                      1
Place                       1
Date                        1
Safety_Device               9
Helemt_Frequency            1
Most_Vulnerable_User        1
ISI_Awareness               1
Youth_Role                  1
Speed_Limit_Knowledge       1
Helmet_Prevention_belief    1
Helmet_Buying_Factor        1
Pillion_Helmet              1
Mirror_Importance           1
Helmet_Type                 0
Influenced_Others           1
Media_Influence             1
Age_Group                   0
dtype: int64

In [91]:
df[df.isnull().any(axis=1)]

,Respondent_ID,Name,Age,Gender,Place,Date,Safety_Device,Helemt_Frequency,Most_Vulnerable_User,ISI_Awareness,Youth_Role,Speed_Limit_Knowledge,Helmet_Prevention_belief,Helmet_Buying_Factor,Pillion_Helmet,Mirror_Importance,Helmet_Type,Influenced_Others,Media_Influence,Age_Group
0,1.0,Govind Yadav,19.0,Male,DTU,10/12/2024,NaN,Always,Two Wheeler,No,Yes,25 KMPH,No,Safety,Always,Very Useful,Standard(ISI Marked),Yes,Yes,18-20
4,5.0,Mayank Yadav,21.0,Male,DTU,10/12/2024,NaN,Always,Two Wheeler,No,Yes,25 KMPH,Yes,Price,Never,Sometime Useful,Standard(ISI Marked),No,Yes,21-25
5,6.0,Nikshep,23.0,Male,DTU,10/12/2024,NaN,Always,Cyclists,No,Yes,40 KMPH,Yes,Safety,Sometimes,Sometime Useful,Standard(ISI Marked),Yes,Yes,21-25
8,9.0,Kalash,23.0,Male,DTU,11/12/2024,NaN,Always,Two Wheeler,No,Yes,25 KMPH,Yes,Price,Sometimes,Very Useful,Standard(ISI Marked),No,Yes,21-25
10,11.0,Kalicharan,33.0,Male,DTU,10/12/2024,NaN,Always,Two Wheeler,No,Yes,25 KMPH,Yes,Safety,Always,Sometime Useful,Non-Standard(Local Mode),Yes,Yes,26+
22,23.0,Gaurav,21.0,Male,DTU,11/12/2024,NaN,Always,Two Wheeler,Yes,Yes,25 KMPH,Yes,Style,Always,Very Useful,Standard(ISI Marked),Yes,Yes,21-25
33,34.0,Saumik,20.0,Male,DTU,10/12/2024,NaN,Always,Two Wheeler,No,Yes,40 KMPH,Yes,Safety,Sometimes,Sometime Useful,Non-Standard(Local Mode),Yes,No,18-20
42,43.0,Jatin,20.0,Male,DTU,10/12/2024,NaN,When needed,Car Driver,No,Yes,30 KMPH,Yes,Brand,Always,Not Useful,Standard(ISI Marked),No,Yes,18-20
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,26+

In [93]:
df.tail()

,Respondent_ID,Name,Age,Gender,Place,Date,Safety_Device,Helemt_Frequency,Most_Vulnerable_User,ISI_Awareness,Youth_Role,Speed_Limit_Knowledge,Helmet_Prevention_belief,Helmet_Buying_Factor,Pillion_Helmet,Mirror_Importance,Helmet_Type,Influenced_Others,Media_Influence,Age_Group
41,42.0,Anshuman,21.0,Male,DTU,10/12/2024,Quality Helmet,Always,Cyclists,Yes,Yes,25 KMPH,Yes,Safety,Always,Very Useful,Standard(ISI Marked),Yes,No,21-25
42,43.0,Jatin,20.0,Male,DTU,10/12/2024,NaN,When needed,Car Driver,No,Yes,30 KMPH,Yes,Brand,Always,Not Useful,Standard(ISI Marked),No,Yes,18-20
43,44.0,Rahul,20.0,Male,DTU,10/12/2024,Quality Helmet,Always,Two Wheeler,Yes,Yes,30 KMPH,Yes,Brand,Always,Very Useful,Non-Standard(Local Mode),Yes,Yes,18-20
44,45.0,Akshat,20.0,Male,DTU,10/12/2024,Quality Helmet,Sometime,Two Wheeler,Yes,Yes,25 KMPH,Yes,Safety,Sometimes,Very Useful,Standard(ISI Marked),Yes,Yes,18-20
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,26+

In [95]:
df.dropna(how="all",inplace=True)

In [97]:
df.isnull().sum()

Respondent_ID               1
Name                        1
Age                         1
Gender                      1
Place                       1
Date                        1
Safety_Device               9
Helemt_Frequency            1
Most_Vulnerable_User        1
ISI_Awareness               1
Youth_Role                  1
Speed_Limit_Knowledge       1
Helmet_Prevention_belief    1
Helmet_Buying_Factor        1
Pillion_Helmet              1
Mirror_Importance           1
Helmet_Type                 0
Influenced_Others           1
Media_Influence             1
Age_Group                   0
dtype: int64

In [99]:
df[df["Safety_Device"].isnull()]

,Respondent_ID,Name,Age,Gender,Place,Date,Safety_Device,Helemt_Frequency,Most_Vulnerable_User,ISI_Awareness,Youth_Role,Speed_Limit_Knowledge,Helmet_Prevention_belief,Helmet_Buying_Factor,Pillion_Helmet,Mirror_Importance,Helmet_Type,Influenced_Others,Media_Influence,Age_Group
0,1.0,Govind Yadav,19.0,Male,DTU,10/12/2024,NaN,Always,Two Wheeler,No,Yes,25 KMPH,No,Safety,Always,Very Useful,Standard(ISI Marked),Yes,Yes,18-20
4,5.0,Mayank Yadav,21.0,Male,DTU,10/12/2024,NaN,Always,Two Wheeler,No,Yes,25 KMPH,Yes,Price,Never,Sometime Useful,Standard(ISI Marked),No,Yes,21-25
5,6.0,Nikshep,23.0,Male,DTU,10/12/2024,NaN,Always,Cyclists,No,Yes,40 KMPH,Yes,Safety,Sometimes,Sometime Useful,Standard(ISI Marked),Yes,Yes,21-25
8,9.0,Kalash,23.0,Male,DTU,11/12/2024,NaN,Always,Two Wheeler,No,Yes,25 KMPH,Yes,Price,Sometimes,Very Useful,Standard(ISI Marked),No,Yes,21-25
10,11.0,Kalicharan,33.0,Male,DTU,10/12/2024,NaN,Always,Two Wheeler,No,Yes,25 KMPH,Yes,Safety,Always,Sometime Useful,Non-Standard(Local Mode),Yes,Yes,26+
22,23.0,Gaurav,21.0,Male,DTU,11/12/2024,NaN,Always,Two Wheeler,Yes,Yes,25 KMPH,Yes,Style,Always,Very Useful,Standard(ISI Marked),Yes,Yes,21-25
33,34.0,Saumik,20.0,Male,DTU,10/12/2024,NaN,Always,Two Wheeler,No,Yes,40 KMPH,Yes,Safety,Sometimes,Sometime Useful,Non-Standard(Local Mode),Yes,No,18-20
42,43.0,Jatin,20.0,Male,DTU,10/12/2024,NaN,When needed,Car Driver,No,Yes,30 KMPH,Yes,Brand,Always,Not Useful,Standard(ISI Marked),No,Yes,18-20
45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,26+

In [101]:
df["Safety_Device"] = df["Safety_Device"].fillna("Not Mentioned")

In [103]:
df["Safety_Device"].value_counts()

Safety_Device
Quality Helmet    37
Not Mentioned      9
Name: count, dtype: int64

In [105]:
df.isnull().sum()

Respondent_ID               1
Name                        1
Age                         1
Gender                      1
Place                       1
Date                        1
Safety_Device               0
Helemt_Frequency            1
Most_Vulnerable_User        1
ISI_Awareness               1
Youth_Role                  1
Speed_Limit_Knowledge       1
Helmet_Prevention_belief    1
Helmet_Buying_Factor        1
Pillion_Helmet              1
Mirror_Importance           1
Helmet_Type                 0
Influenced_Others           1
Media_Influence             1
Age_Group                   0
dtype: int64

In [107]:
df[df.isnull().all(axis=1)]

Empty DataFrame
Columns: [Respondent_ID, Name, Age, Gender , Place , Date, Safety_Device, Helemt_Frequency, Most_Vulnerable_User, ISI_Awareness, Youth_Role, Speed_Limit_Knowledge, Helmet_Prevention_belief, Helmet_Buying_Factor, Pillion_Helmet, Mirror_Importance, Helmet_Type, Influenced_Others, Media_Influence, Age_Group]
Index: []

In [109]:
df.dropna(
    how="all",
    inplace=True
)

In [111]:
df.isnull().sum()

Respondent_ID               1
Name                        1
Age                         1
Gender                      1
Place                       1
Date                        1
Safety_Device               0
Helemt_Frequency            1
Most_Vulnerable_User        1
ISI_Awareness               1
Youth_Role                  1
Speed_Limit_Knowledge       1
Helmet_Prevention_belief    1
Helmet_Buying_Factor        1
Pillion_Helmet              1
Mirror_Importance           1
Helmet_Type                 0
Influenced_Others           1
Media_Influence             1
Age_Group                   0
dtype: int64

In [113]:
df[df.isnull().any(axis=1)]

,Respondent_ID,Name,Age,Gender,Place,Date,Safety_Device,Helemt_Frequency,Most_Vulnerable_User,ISI_Awareness,Youth_Role,Speed_Limit_Knowledge,Helmet_Prevention_belief,Helmet_Buying_Factor,Pillion_Helmet,Mirror_Importance,Helmet_Type,Influenced_Others,Media_Influence,Age_Group
45,NaN,NaN,NaN,NaN,NaN,NaN,Not Mentioned,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,26+

In [115]:
df = df.dropna(how="all")

In [117]:
df.shape

(46, 20)

In [119]:
df.isnull().sum()

Respondent_ID               1
Name                        1
Age                         1
Gender                      1
Place                       1
Date                        1
Safety_Device               0
Helemt_Frequency            1
Most_Vulnerable_User        1
ISI_Awareness               1
Youth_Role                  1
Speed_Limit_Knowledge       1
Helmet_Prevention_belief    1
Helmet_Buying_Factor        1
Pillion_Helmet              1
Mirror_Importance           1
Helmet_Type                 0
Influenced_Others           1
Media_Influence             1
Age_Group                   0
dtype: int64

In [121]:
df[df.isnull().any(axis=1)]

,Respondent_ID,Name,Age,Gender,Place,Date,Safety_Device,Helemt_Frequency,Most_Vulnerable_User,ISI_Awareness,Youth_Role,Speed_Limit_Knowledge,Helmet_Prevention_belief,Helmet_Buying_Factor,Pillion_Helmet,Mirror_Importance,Helmet_Type,Influenced_Others,Media_Influence,Age_Group
45,NaN,NaN,NaN,NaN,NaN,NaN,Not Mentioned,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,26+

In [123]:
pd.set_option('display.max_columns', None)

df[df.isnull().any(axis=1)]

,Respondent_ID,Name,Age,Gender,Place,Date,Safety_Device,Helemt_Frequency,Most_Vulnerable_User,ISI_Awareness,Youth_Role,Speed_Limit_Knowledge,Helmet_Prevention_belief,Helmet_Buying_Factor,Pillion_Helmet,Mirror_Importance,Helmet_Type,Influenced_Others,Media_Influence,Age_Group
45,NaN,NaN,NaN,NaN,NaN,NaN,Not Mentioned,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Unknown,NaN,NaN,26+

In [125]:
df.loc[45]

Respondent_ID                         NaN
Name                                  NaN
Age                                   NaN
Gender                                NaN
Place                                 NaN
Date                                  NaN
Safety_Device               Not Mentioned
Helemt_Frequency                      NaN
Most_Vulnerable_User                  NaN
ISI_Awareness                         NaN
Youth_Role                            NaN
Speed_Limit_Knowledge                 NaN
Helmet_Prevention_belief              NaN
Helmet_Buying_Factor                  NaN
Pillion_Helmet                        NaN
Mirror_Importance                     NaN
Helmet_Type                       Unknown
Influenced_Others                     NaN
Media_Influence                       NaN
Age_Group                             26+
Name: 45, dtype: object

In [127]:
df = df[df["Respondent_ID"].notna()]

In [129]:
df.shape

(45, 20)

In [131]:
df.isnull().sum()

Respondent_ID               0
Name                        0
Age                         0
Gender                      0
Place                       0
Date                        0
Safety_Device               0
Helemt_Frequency            0
Most_Vulnerable_User        0
ISI_Awareness               0
Youth_Role                  0
Speed_Limit_Knowledge       0
Helmet_Prevention_belief    0
Helmet_Buying_Factor        0
Pillion_Helmet              0
Mirror_Importance           0
Helmet_Type                 0
Influenced_Others           0
Media_Influence             0
Age_Group                   0
dtype: int64

In [133]:
df.to_csv(
"LnT_Helmet_Survey_Cleaned.csv",
index=False
)